# Generated by Django 5.0.7 on 2024-07-31 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0002_alter_inventory_owner_alter_inventory_wine_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='location',
        ),
        migrations.RemoveField(
            model_name='wines',
            name='grape',
        ),
        migrations.RemoveField(
            model_name='wines',
            name='type',
        ),
        migrations.DeleteModel(
            name='Prices',
        ),
    ]
